# Generated by Django 5.1.4 on 2025-04-25 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertable',
            name='refferal_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Referral Code'),
        ),
    ]
