# Generated by Django 5.1.4 on 2025-04-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication1', '0002_usertable_referred_by_usertable_refferal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertable',
            old_name='referred_by',
            new_name='refferred_by',
        ),
    ]
