# Generated by Django 5.1.4 on 2025-04-25 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication1', '0003_rename_referred_by_usertable_refferred_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertable',
            old_name='refferred_by',
            new_name='referred_by',
        ),
    ]
