# Generated by Django 5.1.7 on 2025-05-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication1', '0004_rename_refferred_by_usertable_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
