# Generated by Django 5.1.7 on 2025-05-14 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication1', '0005_usertable_is_staff_alter_usertable_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid 10-digit Indian mobile number starting with 6-9.', regex='^[5-9]\\d{9}$')], verbose_name='Phone Number'),
        ),
    ]
