# Generated by Django 5.1.4 on 2025-03-27 13:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandTable',
            fields=[
                ('brand_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConcentrationType',
            fields=[
                ('concentration_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('concentration', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('min_order_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('max_discount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('usage_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fragrance',
            fields=[
                ('fragrance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fragrance_type', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gender_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('occasion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('occasion', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SizeTable',
            fields=[
                ('size_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='adminapp.brandtable')),
                ('concentration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='adminapp.concentrationtype')),
                ('fragrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='adminapp.fragrance')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='adminapp.gender')),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='adminapp.occasion')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='perfume_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adminapp.producttable')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_name', models.CharField(max_length=100)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('applicable_on', models.CharField(choices=[('product', 'Single Product'), ('category', 'Category'), ('all', 'All Products')], max_length=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='adminapp.producttable')),
            ],
        ),
        migrations.CreateModel(
            name='VarienceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varience', to='adminapp.producttable')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varience', to='adminapp.sizetable')),
            ],
        ),
    ]
