# Generated by Django 5.1.7 on 2025-04-18 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=50)),
                ('offer_type', models.CharField(choices=[('brand', 'Brand Offer'), ('product', 'Single Product Offer'), ('special', 'Special Day Offer'), ('seasonal', 'Seasonal Offer')], max_length=20)),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('bogo', 'Buy One Get One'), ('bundle', 'Bundle Discount')], max_length=20, null=True)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_offers', to='adminapp.brandtable')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_offers', to='adminapp.producttable')),
            ],
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
