# Generated by Django 5.1.7 on 2025-04-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_offertable_delete_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offertable',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='offertable',
            name='offer_type',
            field=models.CharField(choices=[('brand', 'Brand Offer'), ('product', 'Single Product Offer')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
