# Generated by Django 5.1.4 on 2025-04-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='applied_coupon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
