# Generated by Django 5.1.4 on 2025-04-23 11:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_cart_applied_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='applied_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
