# Generated by Django 5.1.4 on 2025-04-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='return_date',
            new_name='return_completion_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='return_description',
            new_name='return_reason',
        ),
        migrations.AddField(
            model_name='order',
            name='return_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_status',
            field=models.CharField(blank=True, choices=[('Requested', 'Return Requested'), ('Approved', 'Return Approved'), ('Rejected', 'Return Rejected'), ('Completed', 'Return Completed')], max_length=20, null=True),
        ),
    ]
