# Generated by Django 5.1.4 on 2025-04-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_return_date_order_return_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
