# Generated by Django 5.1.4 on 2025-04-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_order_return_date_order_return_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='return_description',
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_request_status',
            field=models.CharField(blank=True, choices=[('Requested', 'Cancellation Requested'), ('Approved', 'Cancellation Approved'), ('Rejected', 'Cancellation Rejected')], max_length=20, null=True),
        ),
    ]
