# Generated by Django 5.1.4 on 2025-04-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_order_return_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Razorpay', 'Razorpay'), ('Wallet', 'Wallet'), ('Cash on Delivery', 'Cash on Delivery')], default='Cash on Delivery', max_length=20),
        ),
    ]
