# Generated by Django 5.1.4 on 2025-04-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('PAID', 'PAID'), ('Failed', 'Failed'), ('Retry', 'Retry'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
    ]
