# Generated by Django 5.1.4 on 2025-04-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('PAID', 'PAID'), ('failed', 'failed'), ('Retry', 'Retry'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
    ]
