# Generated by Django 5.1.7 on 2025-05-09 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_order_discount_amount_order_grand_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
    ]
